const dataSet = [
  {
    task_name: "General info",
    response: {
      company_information: {
        cin_number: "L63011TN2004PLC054655",
        company_name: "TVS Supply Chain Solutions Limited",
        establish_year: "2004",
        registered_address: "10 Jawahar Road, Chokkikulam, Madurai –625 002, Tamil Nadu, India",
        corporate_address: "No.58, Eldams road, Teynampet Chennai –600 018, Tamil Nadu, India",
        company_email: "cs.compliance@tvsscs.com",
        company_telephone: "+91 44 66857777 (Corporate Office)",
        company_website: "https://tvs.com",
        reporting_year: "1st April 2023-31st March 2024",
        stock_name: "National Stock Exchange of India Limited, BSE Limited",
        capital_paid: "Rs. 44.02 Crores",
        contact_name: "P D Krishna Prasad (Company Secretary and Compliance Officer)",
        contact_details: "Telephone: +91 44 66857777 (Corporate Office) Email address: krishnapr…",
        reporting_boundary: "Disclosures made in this report are on a “Standalone Basis”",
        assurance_name: "For the reporting period, external assurance is notapplicable.",
        assurance_type: "For the reporting period, external assurance is not applicable.",
      },
      business: [
        {
          business_name: "gfdvhgnvb",
          main_activity: "ghcbvnb",
          business_activity: "bvgvnbn",
          business_turnover_rs: "453346",
          business_turnover_percentage: "70",
        },
      ],
      products: [
        {
          product_name: "gdhfgh",
          associated_business: "errftytgh",
          nic_code: "4565655",
          product_turnover_rs: "898978",
          product_turnover_percentage: "80",
        },
      ],
      operations: {
        total_national_plants: "10",
        national_plants: "4",
        national_offices: "6",
        total_international_plants: "8",
        international_plants: "3",
        international_offices: "5",
      },
      location: [
        {
          site_name: "India Operations",
          site_associated_business: "fcgvn",
          site_business_type: "vbvhnvj",
          site_country: "ghjhhjjbn",
          site_location: "Bangalore",
          site_description: "fsdgfj",
          site_type: "Plant",
          site_region: "National",
        },
        {
          site_name: "Global Corporate",
          site_associated_business: "ghhgbmjh",
          site_business_type: "vbvhjh",
          site_location: "Mumbai",
          site_country: "India",
          site_description: "gnhmbbmn",
          site_type: "Plant",
          site_region: "National",
        },
        {
          site_name: "COE",
          site_associated_business: "ghghfjgj",
          site_business_type: "gfghfghfg",
          site_location: "Chennai",
          site_country: "India",
          site_description: "fhgjkjgg",
          site_type: "Office",
          site_region: "International",
        },
      ],
    },
  },
  {
    task_name: "Employee Details",
    response: [
      {
        question_id: "655b37f9615a58e640ec3f94",
        question: "Permanent Female Employee",
        section: "Employee",
        value: "20",
      },
      {
        question_id: "655b37f9615a58e640ec3f95",
        question: "Other than Permanent Male Employee",
        section: "Employee",
        value: "25",
      },
      {
        question_id: "655b37f8615a58e640ec3f93",
        question: "Permanent Male Employee",
        section: "Employee",
        value: "40",
      },
      {
        question_id: "655b37f9615a58e640ec3f96",
        question: "Other than Permanent Female Employee",
        section: "Employee",
        value: "30",
      },
      {
        question_id: "655c81c30c5353d8af0ebb86",
        question: "Permanent Male Worker",
        section: "Worker",
        value: "24",
      },
      {
        question_id: "655c81c30c5353d8af0ebb87",
        question: "Permanent Female Workers",
        section: "Worker",
        value: "23",
      },
      {
        question_id: "655c81c30c5353d8af0ebb88",
        question: "Other than Permanent Male Workers",
        section: "Worker",
        value: "43",
      },
      {
        question_id: "655c81c30c5353d8af0ebb89",
        question: "Other than Permanent Female Workers",
        section: "Worker",
        value: "50",
      },
    ],
  },
  {
    task_name: "Hiring",
    response: [
      {
        question_id: "655d95cd0c5353d8af0ebc1d",
        question: "Permanent Male Employees",
        section: "Breakup by Position",
        value: "5",
      },
      {
        question_id: "655d95cd0c5353d8af0ebc1e",
        question: "Permanent Female Employees",
        section: "Breakup by Position",
        value: "5",
      },
      {
        question_id: "655d95cd0c5353d8af0ebc1f",
        question: "Permanent Male Workers",
        section: "Breakup by Position",
        value: "5",
      },
      {
        question_id: "655d95cd0c5353d8af0ebc20",
        question: "Permanent Female Workers",
        section: "Breakup by Position",
        value: "5",
      },
      {
        question_id: "655d96500c5353d8af0ebc2a",
        question: "30 - 40 Years",
        section: "Breakup by Age Group",
        value: "5",
      },
      {
        question_id: "655d96500c5353d8af0ebc2b",
        question: "40 - 50 Years",
        section: "Breakup by Age Group",
        value: "5",
      },
      {
        question_id: "655d96500c5353d8af0ebc29",
        question: "20 - 30 Years",
        section: "Breakup by Age Group",
        value: "5",
      },
      {
        question_id: "655d96500c5353d8af0ebc2c",
        question: "50 - 58 Years",
        section: "Breakup by Age Group",
        value: "5",
      },
      {
        question_id: "655d96e00c5353d8af0ebc36",
        question: "West",
        section: "Breakup by Region",
        value: "4",
      },
      {
        question_id: "655d96e00c5353d8af0ebc33",
        question: "North",
        section: "Breakup by Region",
        value: "4",
      },
      {
        question_id: "655d96e00c5353d8af0ebc35",
        question: "East ",
        section: "Breakup by Region",
        value: "4",
      },
      {
        question_id: "655d96e00c5353d8af0ebc37",
        question: "South",
        section: "Breakup by Region",
        value: "4",
      },
      {
        question_id: "655d96e00c5353d8af0ebc34",
        question: "North-East ",
        section: "Breakup by Region",
        value: "4",
      },
    ],
  },
  {
    task_name: "Attrition",
    response: [
      {
        question_id: "655da49e0c5353d8af0ebc56",
        question: "20 - 30 Years",
        section: "Breakup by Age Group - Attrition",
        value: "5",
      },
      {
        question_id: "655da49e0c5353d8af0ebc59",
        question: "50 - 58 Years",
        section: "Breakup by Age Group - Attrition",
        value: "5",
      },
      {
        question_id: "655da49e0c5353d8af0ebc57",
        question: "30 - 40 Years",
        section: "Breakup by Age Group - Attrition",
        value: "5",
      },
      {
        question_id: "655da49e0c5353d8af0ebc58",
        question: "40 - 50 Years",
        section: "Breakup by Age Group - Attrition",
        value: "5",
      },
      {
        question_id: "655da49e0c5353d8af0ebc5a",
        question: "Permanent Male Employee",
        section: "Breakup by Position- Attrition",
        value: "5",
      },
      {
        question_id: "655da49e0c5353d8af0ebc5d",
        question: "Permanent Female Workers",
        section: "Breakup by Position- Attrition",
        value: "5",
      },
      {
        question_id: "655da49e0c5353d8af0ebc5c",
        question: "Permanent Male Workers",
        section: "Breakup by Position- Attrition",
        value: "5",
      },
      {
        question_id: "655da49e0c5353d8af0ebc5b",
        question: "Permanent Female Employee",
        section: "Breakup by Position- Attrition",
        value: "5",
      },
      {
        question_id: "655da54a0c5353d8af0ebc6b",
        question: "North-East ",
        section: "Breakup by Region- Attrition",
        value: "4",
      },
      {
        question_id: "655da54a0c5353d8af0ebc6c",
        question: "East",
        section: "Breakup by Region- Attrition",
        value: "4",
      },
      {
        question_id: "655da54a0c5353d8af0ebc6e",
        question: "South",
        section: "Breakup by Region- Attrition",
        value: "4",
      },
      {
        question_id: "655da54a0c5353d8af0ebc6d",
        question: "West",
        section: "Breakup by Region- Attrition",
        value: "4",
      },
      {
        question_id: "655da54a0c5353d8af0ebc6a",
        question: "North",
        section: "Breakup by Region- Attrition",
        value: "4",
      },
    ],
  },
  {
    task_name: "Attrition",
    response: [
      {
        question_id: "655da49e0c5353d8af0ebc56",
        question: "20 - 30 Years",
        section: "Breakup by Age Group - Attrition",
        value: "2",
      },
      {
        question_id: "655da49e0c5353d8af0ebc59",
        question: "50 - 58 Years",
        section: "Breakup by Age Group - Attrition",
        value: "2",
      },
      {
        question_id: "655da49e0c5353d8af0ebc57",
        question: "30 - 40 Years",
        section: "Breakup by Age Group - Attrition",
        value: "2",
      },
      {
        question_id: "655da49e0c5353d8af0ebc58",
        question: "40 - 50 Years",
        section: "Breakup by Age Group - Attrition",
        value: "2",
      },
      {
        question_id: "655da49e0c5353d8af0ebc5a",
        question: "Permanent Male Employee",
        section: "Breakup by Position- Attrition",
        value: "2",
      },
      {
        question_id: "655da49e0c5353d8af0ebc5d",
        question: "Permanent Female Workers",
        section: "Breakup by Position- Attrition",
        value: "2",
      },
      {
        question_id: "655da49e0c5353d8af0ebc5c",
        question: "Permanent Male Workers",
        section: "Breakup by Position- Attrition",
        value: "2",
      },
      {
        question_id: "655da49e0c5353d8af0ebc5b",
        question: "Permanent Female Employee",
        section: "Breakup by Position- Attrition",
        value: "2",
      },
      {
        question_id: "655da54a0c5353d8af0ebc6b",
        question: "North-East ",
        section: "Breakup by Region- Attrition",
        value: "2",
      },
      {
        question_id: "655da54a0c5353d8af0ebc6c",
        question: "East",
        section: "Breakup by Region- Attrition",
        value: "1",
      },
      {
        question_id: "655da54a0c5353d8af0ebc6e",
        question: "South",
        section: "Breakup by Region- Attrition",
        value: "2",
      },
      {
        question_id: "655da54a0c5353d8af0ebc6d",
        question: "West",
        section: "Breakup by Region- Attrition",
        value: "2",
      },
      {
        question_id: "655da54a0c5353d8af0ebc6a",
        question: "North",
        section: "Breakup by Region- Attrition",
        value: "1",
      },
    ],
  },
  {
    task_name: "VRS/ Retirement",
    response: [
      {
        question_id: "655dab120c5353d8af0ebd00",
        question: "Number of new employees who left the organisation",
        section: "VRS / Retirement - age, gender, region",
        value: "10",
      },
      {
        question_id: "655dab860c5353d8af0ebd05",
        question: "30 - 40 Years",
        section: "Breakup by Age Group- VRS",
        value: "3",
      },
      {
        question_id: "655dab860c5353d8af0ebd07",
        question: "50 - 58 Years",
        section: "Breakup by Age Group- VRS",
        value: "3",
      },
      {
        question_id: "655dab860c5353d8af0ebd04",
        question: "20 - 30 Years",
        section: "Breakup by Age Group- VRS",
        value: "2",
      },
      {
        question_id: "655dab860c5353d8af0ebd06",
        question: "40 - 50 Years",
        section: "Breakup by Age Group- VRS",
        value: "2",
      },
      {
        question_id: "655dabea0c5353d8af0ebd0e",
        question: "Male",
        section: "Breakup by Gender-VRS",
        value: "7",
      },
      {
        question_id: "655dabea0c5353d8af0ebd0f",
        question: "Female",
        section: "Breakup by Gender-VRS",
        value: "3",
      },
      {
        question_id: "655dac590c5353d8af0ebd1c",
        question: "South",
        section: "Breakup by Region- VRS",
        value: "2",
      },
      {
        question_id: "655dac590c5353d8af0ebd18",
        question: "North",
        section: "Breakup by Region- VRS",
        value: "2",
      },
      {
        question_id: "655dac590c5353d8af0ebd19",
        question: "North-East ",
        section: "Breakup by Region- VRS",
        value: "2",
      },
      {
        question_id: "655dac590c5353d8af0ebd1a",
        question: "East",
        section: "Breakup by Region- VRS",
        value: "2",
      },
      {
        question_id: "655dac590c5353d8af0ebd1b",
        question: "West",
        section: "Breakup by Region- VRS",
        value: "2",
      },
    ],
  },
  {
    task_name: "Differentlyabled Manpower",
    response: [
      {
        question_id: "655c8b340c5353d8af0ebb96",
        question: "Special Category Like LGBTQA+ ",
        section: "Employees with Special Abilities",
        value: "0",
      },
      {
        question_id: "655c8b340c5353d8af0ebb95",
        question: "Employees with Disabilities",
        section: "Employees with Special Abilities",
        value: "2",
      },
      {
        question_id: "655c8d1a0c5353d8af0ebb9b",
        question: "Permanent male employees",
        section: "Differentially abled employees",
        value: "1",
      },
      {
        question_id: "655c8d1a0c5353d8af0ebb9c",
        question: "Permanent female employees",
        section: "Differentially abled employees",
        value: "0",
      },
      {
        question_id: "655c90c60c5353d8af0ebba2",
        question: "Other than Permanent Female Employees",
        section: "Differentially abled employees",
        value: "1",
      },
      {
        question_id: "655c90c60c5353d8af0ebba1",
        question: "Other than Permanent Male Employees",
        section: "Differentially abled employees",
        value: "0",
      },
      {
        question_id: "655c978f0c5353d8af0ebbba",
        question: "Other than Permanent Male Workers",
        section: "Differentially abled workers",
        value: "0",
      },
      {
        question_id: "655c978f0c5353d8af0ebbb9",
        question: "Permanent Female Workers",
        section: "Differentially abled workers",
        value: "0",
      },
      {
        question_id: "655c978f0c5353d8af0ebbbb",
        question: "Other than Permanent Female Workers",
        section: "Differentially abled workers",
        value: "0",
      },
      {
        question_id: "655c978f0c5353d8af0ebbb8",
        question: "Permanent Male Workers",
        section: "Differentially abled workers",
        value: "0",
      },
    ],
  },
  {
    task_name: "Remuneration",
    response: [
      {
        question_id: "65618fa298f8d6efd473802e",
        question: "Male",
        section: "Employees",
        value: "50",
      },
      {
        question_id: "65618fa298f8d6efd473802f",
        question: "Female ",
        section: "Employees",
        value: "60",
      },
      {
        question_id: "6561901398f8d6efd4738035",
        question: "Female ",
        section: "Workers",
        value: "60",
      },
      {
        question_id: "6561901398f8d6efd4738034",
        question: "Male",
        section: "Workers",
        value: "60",
      },
    ],
  },
  {
    task_name: "Median Pay",
    response: [
      {
        question_id: "6561921c98f8d6efd473803b",
        question: "Female ",
        section: "Board of Director",
        value: "2",
      },
      {
        question_id: "6561921c98f8d6efd473803c",
        question: "Percentage on-Time Payment (BoD)",
        section: "Board of Director",
        value: "90",
      },
      {
        question_id: "6561921c98f8d6efd473803d",
        question: "Average Days of Delay (BoD)",
        section: "Board of Director",
        value: "5",
      },
      {
        question_id: "6561921c98f8d6efd473803a",
        question: "Male",
        section: "Board of Director",
        value: "2",
      },
      {
        question_id: "6561947198f8d6efd4738066",
        question: "Percentage on-Time Payment ",
        section: "Key Management Personnel",
        value: "95",
      },
      {
        question_id: "6561947198f8d6efd4738064",
        question: "Male",
        section: "Key Management Personnel",
        value: "2",
      },
      {
        question_id: "6561947198f8d6efd4738065",
        question: "Female ",
        section: "Key Management Personnel",
        value: "2",
      },
      {
        question_id: "6561947198f8d6efd4738067",
        question: "Average Days of Delay ",
        section: "Key Management Personnel",
        value: "3",
      },
      {
        question_id: "656195ba98f8d6efd4738073",
        question: "Average Days Of Delay",
        section: "Employees Other than KMP",
        value: "3",
      },
      {
        question_id: "656195ba98f8d6efd4738071",
        question: "Female ",
        section: "Employees Other than KMP",
        value: "2",
      },
      {
        question_id: "656195ba98f8d6efd4738070",
        question: "Male",
        section: "Employees Other than KMP",
        value: "2",
      },
      {
        question_id: "656195ba98f8d6efd4738072",
        question: "Percentage on-Time Payment ",
        section: "Employees Other than KMP",
        value: "95",
      },
      {
        question_id: "6561977136946287f6917ff6",
        question: "Percentage on-time Payment",
        section: "Contract ",
        value: "98",
      },
      {
        question_id: "6561977136946287f6917ff5",
        question: "Female",
        section: "Contract ",
        value: "2",
      },
      {
        question_id: "6561977136946287f6917ff7",
        question: "Average days of Delay",
        section: "Contract ",
        value: "2",
      },
      {
        question_id: "6561977136946287f6917ff4",
        question: "Male",
        section: "Contract ",
        value: "2",
      },
    ],
  },
  {
    task_name: "Union Membership",
    response: [
      {
        question_id: "655dadcb0c5353d8af0ebd24",
        question: "Name of the Union - 1",
        section: "Union Membership- employees & workers",
        value: "50",
      },
      {
        question_id: "655daeb00c5353d8af0ebd28",
        question: "Male",
        section: "Permanent Employees",
        value: "20",
      },
      {
        question_id: "655daeb00c5353d8af0ebd29",
        question: "Female",
        section: "Permanent Employees",
        value: "10",
      },
      {
        question_id: "655daf210c5353d8af0ebd2f",
        question: "Female",
        section: "Permanent Workers",
        value: "10",
      },
      {
        question_id: "655daf210c5353d8af0ebd2e",
        question: "Male",
        section: "Permanent Workers",
        value: "10",
      },
    ],
  },
  {
    task_name: "Health Insurance",
    response: [
      {
        question_id: "65619d4998f8d6efd4738080",
        question: "Female ",
        section: "Permanent Employees",
        value: "70",
      },
      {
        question_id: "65619d4998f8d6efd473807f",
        question: "Male",
        section: "Permanent Employees",
        value: "60",
      },
      {
        question_id: "65619e4698f8d6efd4738086",
        question: "Female ",
        section: "Other than Permanent Employees",
        value: "30",
      },
      {
        question_id: "65619e4698f8d6efd4738085",
        question: "Male",
        section: "Other than Permanent Employees",
        value: "19",
      },
      {
        question_id: "65619ed998f8d6efd473808c",
        question: "Employees",
        section: "Percentage Employees Covered",
        value: "100",
      },
      {
        question_id: "65619ed998f8d6efd473808b",
        question: "On roll",
        section: "Percentage Employees Covered",
        value: "40",
      },
      {
        question_id: "6561a11198f8d6efd4738092",
        question: "Employees",
        section: "No's of employees availed insurance",
        value: "50",
      },
      {
        question_id: "6561a11198f8d6efd4738091",
        question: "On-Roll",
        section: "No's of employees availed insurance",
        value: "10",
      },
      {
        question_id: "6561a92998f8d6efd473809d",
        question: "Female ",
        section: "Permanent Workers",
        value: "35",
      },
      {
        question_id: "6561a92998f8d6efd473809c",
        question: "Male",
        section: "Permanent Workers",
        value: "40",
      },
      {
        question_id: "6561aa3698f8d6efd47380a9",
        question: "Female ",
        section: "Other than Permanent Workers",
        value: "35",
      },
      {
        question_id: "6561aa3698f8d6efd47380a8",
        question: "Male ",
        section: "Other than Permanent Workers",
        value: "45",
      },
      {
        question_id: "6561aab698f8d6efd47380ae",
        question: "On-Roll",
        section: "Percentage Workers Covered",
        value: "30",
      },
      {
        question_id: "6561aab698f8d6efd47380af",
        question: "Worker",
        section: "Percentage Workers Covered",
        value: "40",
      },
      {
        question_id: "6561ab3498f8d6efd47380b5",
        question: "Worker",
        section: "No's of workers availed insurance",
        value: "50",
      },
      {
        question_id: "6561ab3498f8d6efd47380b4",
        question: "On-Roll",
        section: "No's of workers availed insurance",
        value: "35",
      },
    ],
  },
  {
    task_name: "Accident Insurance",
    response: [
      {
        question_id: "6561ce4998f8d6efd47380c7",
        question: "Female ",
        section: "Permanent Employees",
        value: "50",
      },
      {
        question_id: "6561ce4998f8d6efd47380c6",
        question: "Male",
        section: "Permanent Employees",
        value: "60",
      },
      {
        question_id: "6561cebf98f8d6efd47380cc",
        question: "Male",
        section: "Other than Permanent Employees",
        value: "35",
      },
      {
        question_id: "6561cebf98f8d6efd47380cd",
        question: "Female ",
        section: "Other than Permanent Employees",
        value: "45",
      },
      {
        question_id: "6561cf5498f8d6efd47380d3",
        question: "Employees",
        section: "Percentage Employees Covered",
        value: "30",
      },
      {
        question_id: "6561cf5498f8d6efd47380d2",
        question: "On-Roll",
        section: "Percentage Employees Covered",
        value: "25",
      },
      {
        question_id: "6561d39098f8d6efd47380d9",
        question: "Employees ",
        section: "No's of employees  availed insurance",
        value: "30",
      },
      {
        question_id: "6561d39098f8d6efd47380d8",
        question: "On-Roll",
        section: "No's of employees  availed insurance",
        value: "30",
      },
      {
        question_id: "6561def698f8d6efd47380f3",
        question: "Male",
        section: "Permanent Workers",
        value: "35",
      },
      {
        question_id: "6561def698f8d6efd47380f4",
        question: "Female ",
        section: "Permanent Workers",
        value: "45",
      },
      {
        question_id: "6561df6e98f8d6efd47380fa",
        question: "Female ",
        section: "Other than Permanent Workers",
        value: "50",
      },
      {
        question_id: "6561df6e98f8d6efd47380f9",
        question: "Male",
        section: "Other than Permanent Workers",
        value: "35",
      },
      {
        question_id: "6561dff998f8d6efd47380ff",
        question: "On-Roll",
        section: "Percentage Workers Covered",
        value: "35",
      },
      {
        question_id: "6561dff998f8d6efd4738100",
        question: "Worker",
        section: "Percentage Workers Covered",
        value: "40",
      },
      {
        question_id: "6561e06698f8d6efd4738106",
        question: "Worker",
        section: "No's of workers availed insurance",
        value: "35",
      },
      {
        question_id: "6561e06698f8d6efd4738105",
        question: "On-Roll",
        section: "No's of workers availed insurance",
        value: "40",
      },
    ],
  },
  {
    task_name: "Daycare Benefits",
    response: [
      {
        question_id: "6561e85898f8d6efd4738165",
        question: "Male",
        section: "On-Roll",
        value: "20",
      },
      {
        question_id: "6561e85898f8d6efd4738166",
        question: "Female ",
        section: "On-Roll",
        value: "20",
      },
      {
        question_id: "6561e8ae98f8d6efd473816b",
        question: "Male",
        section: "Employees",
        value: "25",
      },
      {
        question_id: "6561e8ae98f8d6efd473816c",
        question: "Female ",
        section: "Employees",
        value: "25",
      },
      {
        question_id: "6561e96698f8d6efd4738172",
        question: "Employees",
        section: "Percentage Employees Covered",
        value: "100",
      },
      {
        question_id: "6561e96698f8d6efd4738171",
        question: "On-Roll",
        section: "Percentage Employees Covered",
        value: "85",
      },
      {
        question_id: "6561e9d198f8d6efd4738178",
        question: "Employees",
        section: "No's of employees availed day care facilitie",
        value: "30",
      },
      {
        question_id: "6561e9d198f8d6efd4738177",
        question: "On-Roll",
        section: "No's of employees availed day care facilitie",
        value: "25",
      },
      {
        question_id: "6561ea2098f8d6efd473817e",
        question: "Female ",
        section: "Permanent Workers",
        value: "50",
      },
      {
        question_id: "6561ea2098f8d6efd473817d",
        question: "Male",
        section: "Permanent Workers",
        value: "60",
      },
      {
        question_id: "6561ec9898f8d6efd473819c",
        question: "Female ",
        section: "Other than Permanent Workers",
        value: "10",
      },
      {
        question_id: "6561ec9898f8d6efd473819b",
        question: "Male",
        section: "Other than Permanent Workers",
        value: "15",
      },
      {
        question_id: "6561ed1798f8d6efd47381a2",
        question: "Worker",
        section: "Percentage Workers Covered",
        value: "100",
      },
      {
        question_id: "6561ed1798f8d6efd47381a1",
        question: "On roll",
        section: "Percentage Workers Covered",
        value: "85",
      },
      {
        question_id: "6561ed8698f8d6efd47381a8",
        question: "Worker",
        section: "No's of workers availed day care facilities",
        value: "25",
      },
      {
        question_id: "6561ed8698f8d6efd47381a7",
        question: "On-Roll",
        section: "No's of workers availed day care facilities",
        value: "25",
      },
    ],
  },
  {
    task_name: "PF Payments",
    response: [
      {
        question_id: "65641e5698f8d6efd47381cd",
        question: "Number of employees under scope",
        section: "On-Roll",
        value: "50",
      },
      {
        question_id: "65641e5698f8d6efd47381ce",
        question: "On-time collection and deposit with authorities",
        section: "On-Roll",
        value: "50",
      },
      {
        question_id: "65641ea998f8d6efd47381d3",
        question: "Number of employees under scope",
        section: "Contract",
        value: "50",
      },
      {
        question_id: "65641ea998f8d6efd47381d4",
        question: "On-time collection and deposit with authorities",
        section: "Contract",
        value: "50",
      },
    ],
  },
  {
    task_name: "Policies",
    response: [
      {
        question_id: "6564220b98f8d6efd473821f",
        question: "Policy-2",
        section: "List of policies  that the company has",
        value: "2",
      },
      {
        question_id: "6564220b98f8d6efd473821e",
        question: "Policy-1",
        section: "List of policies  that the company has",
        value: "3",
      },
    ],
  },
  {
    task_name: "Participation",
    response: [
      {
        question_id: "655ca3050c5353d8af0ebbe7",
        question: "Total Number of Board of Directors",
        section: "Board of Director",
        value: "5",
      },
      {
        question_id: "655ca3050c5353d8af0ebbe8",
        question: "Women Board of Directors",
        section: "Board of Director",
        value: "3",
      },
      {
        question_id: "655ca4df0c5353d8af0ebbf6",
        question: "Total Number of Key Managerial Personel",
        section: "Key Managerial Personnel",
        value: "1",
      },
      {
        question_id: "655ca4df0c5353d8af0ebbf7",
        question: "Women Key Managerial Personnel",
        section: "Key Managerial Personnel",
        value: "0",
      },
    ],
  },
  {
    task_name: "Canteen Benefit",
    response: [
      {
        question_id: "6561ee1a98f8d6efd47381b0",
        question: "Employees using the facility",
        section: "On-Roll",
        value: "100",
      },
      {
        question_id: "6561eed798f8d6efd47381b4",
        question: "Employees using the facility",
        section: "Contract",
        value: "50",
      },
    ],
  },
  {
    task_name: "Workplace Audit",
    response: [
      {
        question_id: "6564242b98f8d6efd4738235",
        question: "% Compliance",
        section: "Child Labour Compliance",
        value: "100",
      },
      {
        question_id: "6564242b98f8d6efd4738236",
        question: "No's of pending compliant cases",
        section: "Child Labour Compliance",
        value: "0",
      },
      {
        question_id: "6564242b98f8d6efd4738234",
        question: "Percentage sites audited",
        section: "Child Labour Compliance",
        value: "100",
      },
      {
        question_id: "656424a398f8d6efd4738241",
        question: "No's of pending compliant cases",
        section: "Forced / Involuntary Labour Compliance",
        value: "0",
      },
      {
        question_id: "656424a398f8d6efd4738240",
        question: "% Compliance",
        section: "Forced / Involuntary Labour Compliance",
        value: "100",
      },
      {
        question_id: "656424a398f8d6efd473823f",
        question: "Percentage sites audited",
        section: "Forced / Involuntary Labour Compliance",
        value: "100",
      },
      {
        question_id: "6564250898f8d6efd473824c",
        question: "No's of pending compliant cases",
        section: "Sexual Harassment  Compliance",
        value: "0",
      },
      {
        question_id: "6564250898f8d6efd473824b",
        question: "% Compliance",
        section: "Sexual Harassment  Compliance",
        value: "100",
      },
      {
        question_id: "6564250898f8d6efd473824a",
        question: "Percentage sites audited",
        section: "Sexual Harassment  Compliance",
        value: "100",
      },
      {
        question_id: "6564256498f8d6efd4738256",
        question: "% Compliance",
        section: "Discrimination at workplace Compliance",
        value: "100",
      },
      {
        question_id: "6564256498f8d6efd4738257",
        question: "No's of pending compliant cases",
        section: "Discrimination at workplace Compliance",
        value: "0",
      },
      {
        question_id: "6564256498f8d6efd4738255",
        question: "Percentage sites audited",
        section: "Discrimination at workplace Compliance",
        value: "99",
      },
      {
        question_id: "656425c798f8d6efd4738262",
        question: "No's of pending compliant cases",
        section: "Wages Compliance",
        value: "0",
      },
      {
        question_id: "656425c798f8d6efd4738260",
        question: "Percentage sites audited",
        section: "Wages Compliance",
        value: "100",
      },
      {
        question_id: "656425c798f8d6efd4738261",
        question: "% Compliance",
        section: "Wages Compliance",
        value: "100",
      },
      {
        question_id: "6564265898f8d6efd473826d",
        question: "No's of pending compliant cases",
        section: "Other Compliance",
        value: "0",
      },
      {
        question_id: "6564265898f8d6efd473826b",
        question: "Percentage sites audited",
        section: "Other Compliance",
        value: "100",
      },
      {
        question_id: "6564265898f8d6efd473826c",
        question: "% Compliance",
        section: "Other Compliance",
        value: "100",
      },
    ],
  },
  {
    task_name: "Term Based Insurance Plan",
    response: [
      {
        question_id: "6561ef6d98f8d6efd47381be",
        question: "Number of employees covered",
        section: "On-Roll",
        value: "50",
      },
      {
        question_id: "6561efdf98f8d6efd47381c2",
        question: "Number of employees covered",
        section: "Contract",
        value: "50",
      },
    ],
  },
  {
    task_name: "Death Based Compensation",
    response: [
      {
        question_id: "656539fc6f9ee8be6931de1d",
        question: "Number of employees covered",
        section: "On-Roll",
        value: "100",
      },
      {
        question_id: "65653a6c6f9ee8be6931de22",
        question: "Number of employees covered",
        section: "Contract",
        value: "100",
      },
    ],
  },
  {
    task_name: "Maternity Benefit",
    response: [
      {
        question_id: "6561e0ea98f8d6efd4738110",
        question: "Women who have returned back to workplace post Maternity",
        section: "Permanent Employees",
        value: "3",
      },
      {
        question_id: "6561e0ea98f8d6efd473810f",
        question: "Women who have availed the policy",
        section: "Permanent Employees",
        value: "3",
      },
      {
        question_id: "6561e0ea98f8d6efd4738111",
        question: "Women retained 12 months post Maternity",
        section: "Permanent Employees",
        value: "0",
      },
      {
        question_id: "6561e0ea98f8d6efd473810e",
        question: "Women under scope",
        section: "Permanent Employees",
        value: "0",
      },
      {
        question_id: "6561e1d098f8d6efd473811a",
        question: "Women who have returned back to workplace post Maternity",
        section: "Other than Permanent Employees",
        value: "1",
      },
      {
        question_id: "6561e1d098f8d6efd4738118",
        question: "Women under scope",
        section: "Other than Permanent Employees",
        value: "1",
      },
      {
        question_id: "6561e1d098f8d6efd473811b",
        question: "Women retained 12 months post Maternity",
        section: "Other than Permanent Employees",
        value: "0",
      },
      {
        question_id: "6561e1d098f8d6efd4738119",
        question: "Women who have availed the policy",
        section: "Other than Permanent Employees",
        value: "0",
      },
      {
        question_id: "6561e24498f8d6efd4738122",
        question: "Women under scope",
        section: "Permanent Workers",
        value: "1",
      },
      {
        question_id: "6561e24498f8d6efd4738123",
        question: "Women who have availed the policy",
        section: "Permanent Workers",
        value: "0",
      },
      {
        question_id: "6561e24498f8d6efd4738125",
        question: "Women retained 12 months post Maternity",
        section: "Permanent Workers",
        value: "0",
      },
      {
        question_id: "6561e24498f8d6efd4738124",
        question: "Women who have returned back to workplace post Maternity",
        section: "Permanent Workers",
        value: "0",
      },
      {
        question_id: "6561e2b998f8d6efd473812c",
        question: "Women under scope",
        section: "Other than Permanent Workers",
        value: "1",
      },
      {
        question_id: "6561e2b998f8d6efd473812e",
        question: "Women who have returned back to workplace post Maternity",
        section: "Other than Permanent Workers",
        value: "0",
      },
      {
        question_id: "6561e2b998f8d6efd473812f",
        question: "Women retained 12 months post Maternity",
        section: "Other than Permanent Workers",
        value: "1",
      },
      {
        question_id: "6561e2b998f8d6efd473812d",
        question: "Women who have availed the policy",
        section: "Other than Permanent Workers",
        value: "0",
      },
    ],
  },
  {
    task_name: "Paternity Benefit",
    response: [
      {
        question_id: "6561e34e98f8d6efd473813c",
        question: "Men retained 12 months post Paternity",
        section: "Permanent Employees",
        value: "10",
      },
      {
        question_id: "6561e34e98f8d6efd4738139",
        question: "Men under scope",
        section: "Permanent Employees",
        value: "5",
      },
      {
        question_id: "6561e34e98f8d6efd473813a",
        question: "Men who have availed the policy",
        section: "Permanent Employees",
        value: "5",
      },
      {
        question_id: "6561e34e98f8d6efd473813b",
        question: "Men who have returned back to workplace post Paternity",
        section: "Permanent Employees",
        value: "5",
      },
      {
        question_id: "6561e3dc98f8d6efd4738146",
        question: "Men retained 12 months post Paternity",
        section: "Other than permanent employees",
        value: "10",
      },
      {
        question_id: "6561e3dc98f8d6efd4738144",
        question: "Men who have availed the policy",
        section: "Other than permanent employees",
        value: "5",
      },
      {
        question_id: "6561e3dc98f8d6efd4738143",
        question: "Men under scope",
        section: "Other than permanent employees",
        value: "5",
      },
      {
        question_id: "6561e3dc98f8d6efd4738145",
        question: "Men who have returned back to workplace post Paternity",
        section: "Other than permanent employees",
        value: "5",
      },
      {
        question_id: "6561e42a98f8d6efd4738150",
        question: "Men retained 12 months post Paternity",
        section: "Permanent Workers",
        value: "10",
      },
      {
        question_id: "6561e42a98f8d6efd473814e",
        question: "Men who have availed the policy",
        section: "Permanent Workers",
        value: "5",
      },
      {
        question_id: "6561e42a98f8d6efd473814d",
        question: "Men under scope",
        section: "Permanent Workers",
        value: "5",
      },
      {
        question_id: "6561e42a98f8d6efd473814f",
        question: "Men who have returned back to workplace post Paternity",
        section: "Permanent Workers",
        value: "4",
      },
      {
        question_id: "6561e4a998f8d6efd4738158",
        question: "Men who have availed the policy",
        section: "Other than permanent workers",
        value: "10",
      },
      {
        question_id: "6561e4a998f8d6efd4738157",
        question: "Men under scope",
        section: "Other than permanent workers",
        value: "5",
      },
      {
        question_id: "6561e4a998f8d6efd473815a",
        question: "Men retained 12 months post Paternity",
        section: "Other than permanent workers",
        value: "5",
      },
      {
        question_id: "6561e4a998f8d6efd4738159",
        question: "Men who have returned back to workplace post Paternity",
        section: "Other than permanent workers",
        value: "5",
      },
    ],
  },
  {
    task_name: "ESI Payments",
    response: [
      {
        question_id: "65641f1d98f8d6efd47381dd",
        question: "On-time collection and deposit with authorities",
        section: "On-Roll",
        value: "10",
      },
      {
        question_id: "65641f1d98f8d6efd47381dc",
        question: "Number of employees under scope",
        section: "On-Roll",
        value: "10",
      },
      {
        question_id: "65641f5698f8d6efd47381e3",
        question: "On-time collection and deposit with authorities",
        section: "Contract",
        value: "10",
      },
      {
        question_id: "65641f5698f8d6efd47381e2",
        question: "Number of employees under scope",
        section: "Contract",
        value: "10",
      },
    ],
  },
  {
    task_name: "PT Payments",
    response: [
      {
        question_id: "65641fbb98f8d6efd47381ec",
        question: "On-time collection and deposit with authorities",
        section: "On-Roll",
        value: "10",
      },
      {
        question_id: "65641fbb98f8d6efd47381eb",
        question: "Number of employees under scope",
        section: "On-Roll",
        value: "5",
      },
      {
        question_id: "65641fff98f8d6efd47381f2",
        question: "On-time collection and deposit with authorities",
        section: "Contract",
        value: "10",
      },
      {
        question_id: "65641fff98f8d6efd47381f1",
        question: "Number of employees under scope",
        section: "Contract",
        value: "4",
      },
    ],
  },
  {
    task_name: "Gratuity Payments",
    response: [
      {
        question_id: "6564216998f8d6efd4738210",
        question: "On-time collection and deposit with authorities",
        section: "On-Roll",
        value: "10",
      },
      {
        question_id: "6564216998f8d6efd473820f",
        question: "Number of employees under scope",
        section: "On-Roll",
        value: "5",
      },
      {
        question_id: "656421a298f8d6efd4738216",
        question: "On-time collection and deposit with authorities",
        section: "Contract",
        value: "10",
      },
      {
        question_id: "656421a298f8d6efd4738215",
        question: "Number of employees under scope",
        section: "Contract",
        value: "5",
      },
    ],
  },
  {
    task_name: "Manpower Details",
    response: [
      {
        question_id: "663ca4fb018cd84bee1295a9",
        question: "Permanent Employees",
        section: "Employees",
        value: "100",
      },
      {
        question_id: "663ca4fb018cd84bee1295aa",
        question: "Other than Permanent Employees",
        section: "Employees",
        value: "50",
      },
    ],
  },
  {
    task_name: "Hiring",
    response: [
      {
        question_id: "655d95cd0c5353d8af0ebc1d",
        question: "Permanent Male Employees",
        section: "Breakup by Position",
        value: "10",
      },
      {
        question_id: "655d95cd0c5353d8af0ebc1e",
        question: "Permanent Female Employees",
        section: "Breakup by Position",
        value: "10",
      },
      {
        question_id: "655d95cd0c5353d8af0ebc1f",
        question: "Permanent Male Workers",
        section: "Breakup by Position",
        value: "10",
      },
      {
        question_id: "655d95cd0c5353d8af0ebc20",
        question: "Permanent Female Workers",
        section: "Breakup by Position",
        value: "10",
      },
      {
        question_id: "655d96500c5353d8af0ebc2a",
        question: "30 - 40 Years",
        section: "Breakup by Age Group",
        value: "9",
      },
      {
        question_id: "655d96500c5353d8af0ebc2b",
        question: "40 - 50 Years",
        section: "Breakup by Age Group",
        value: "10",
      },
      {
        question_id: "655d96500c5353d8af0ebc29",
        question: "20 - 30 Years",
        section: "Breakup by Age Group",
        value: "10",
      },
      {
        question_id: "655d96500c5353d8af0ebc2c",
        question: "50 - 58 Years",
        section: "Breakup by Age Group",
        value: "10",
      },
      {
        question_id: "655d96e00c5353d8af0ebc36",
        question: "West",
        section: "Breakup by Region",
        value: "10",
      },
      {
        question_id: "655d96e00c5353d8af0ebc33",
        question: "North",
        section: "Breakup by Region",
        value: "5",
      },
      {
        question_id: "655d96e00c5353d8af0ebc35",
        question: "East ",
        section: "Breakup by Region",
        value: "10",
      },
      {
        question_id: "655d96e00c5353d8af0ebc37",
        question: "South",
        section: "Breakup by Region",
        value: "5",
      },
      {
        question_id: "655d96e00c5353d8af0ebc34",
        question: "North-East ",
        section: "Breakup by Region",
        value: "10",
      },
    ],
  },
  {
    task_name: "Employee Details",
    response: [
      {
        question_id: "655b37f9615a58e640ec3f94",
        question: "Permanent Female Employee",
        section: "Employee",
        value: "10",
      },
      {
        question_id: "655b37f9615a58e640ec3f95",
        question: "Other than Permanent Male Employee",
        section: "Employee",
        value: "10",
      },
      {
        question_id: "655b37f8615a58e640ec3f93",
        question: "Permanent Male Employee",
        section: "Employee",
        value: "10",
      },
      {
        question_id: "655b37f9615a58e640ec3f96",
        question: "Other than Permanent Female Employee",
        section: "Employee",
        value: "10",
      },
      {
        question_id: "655c81c30c5353d8af0ebb86",
        question: "Permanent Male Worker",
        section: "Worker",
        value: "5",
      },
      {
        question_id: "655c81c30c5353d8af0ebb87",
        question: "Permanent Female Workers",
        section: "Worker",
        value: "5",
      },
      {
        question_id: "655c81c30c5353d8af0ebb88",
        question: "Other than Permanent Male Workers",
        section: "Worker",
        value: "5",
      },
      {
        question_id: "655c81c30c5353d8af0ebb89",
        question: "Other than Permanent Female Workers",
        section: "Worker",
        value: "5",
      },
    ],
  },
  {
    task_name: "Employee Details",
    response: [
      {
        question_id: "655b37f9615a58e640ec3f94",
        question: "Permanent Female Employee",
        section: "Employee",
        value: "10",
      },
      {
        question_id: "655b37f9615a58e640ec3f95",
        question: "Other than Permanent Male Employee",
        section: "Employee",
        value: "10",
      },
      {
        question_id: "655b37f8615a58e640ec3f93",
        question: "Permanent Male Employee",
        section: "Employee",
        value: "10",
      },
      {
        question_id: "655b37f9615a58e640ec3f96",
        question: "Other than Permanent Female Employee",
        section: "Employee",
        value: "10",
      },
      {
        question_id: "655c81c30c5353d8af0ebb86",
        question: "Permanent Male Worker",
        section: "Worker",
        value: "10",
      },
      {
        question_id: "655c81c30c5353d8af0ebb87",
        question: "Permanent Female Workers",
        section: "Worker",
        value: "10",
      },
      {
        question_id: "655c81c30c5353d8af0ebb88",
        question: "Other than Permanent Male Workers",
        section: "Worker",
        value: "10",
      },
      {
        question_id: "655c81c30c5353d8af0ebb89",
        question: "Other than Permanent Female Workers",
        section: "Worker",
        value: "10",
      },
    ],
  },
];

module.exports = dataSet;