const legalDataSet = [
  {
    task_name: "Anti-Bribery Cases",
    response: [
      {
        question_id: "6582d2b32dbd03ad2d9f17d6",
        question: "Complaints resolved",
        section: "Anti-Bribery Policy",
        value: "9",
      },
      {
        question_id: "6582d2b32dbd03ad2d9f17d5",
        question: "No's Complaints",
        section: "Anti-Bribery Policy",
        value: "10",
      },
      {
        question_id: "6582d2b32dbd03ad2d9f17d7",
        question: "No's of complaints investigated",
        section: "Anti-Bribery Policy",
        value: "10",
      },
      {
        question_id: "6582d2b32dbd03ad2d9f17d8",
        question: "Investigations completed",
        section: "Anti-Bribery Policy",
        value: "9",
      },
      {
        question_id: "6582d2b32dbd03ad2d9f17d9",
        question: "Resolution",
        section: "Anti-Bribery Policy",
        value: "1",
      },
      {
        question_id: "6582d3e62dbd03ad2d9f17e3",
        question: "Directors",
        section: "Action taken on anti-bribery / corruption cases",
        value: "10",
      },
      {
        question_id: "6582d3e62dbd03ad2d9f17e5",
        question: "Employees",
        section: "Action taken on anti-bribery / corruption cases",
        value: "15",
      },
      {
        question_id: "6582d3e62dbd03ad2d9f17e6",
        question: "Workers",
        section: "Action taken on anti-bribery / corruption cases",
        value: "20",
      },
      {
        question_id: "6582d3e62dbd03ad2d9f17e4",
        question: "KMP",
        section: "Action taken on anti-bribery / corruption cases",
        value: "10",
      },
    ],
  },
  {
    task_name: "Conflict of interest cases",
    response: [
      {
        question_id: "65852923304e64caaaeb3cc0",
        question: "Investigations completed",
        section: "Directors",
        value: "10",
      },
      {
        question_id: "65852923304e64caaaeb3cbf",
        question: "No's of complaints investigated",
        section: "Directors",
        value: "10",
      },
      {
        question_id: "65852923304e64caaaeb3cbe",
        question: "Complaints received",
        section: "Directors",
        value: "10",
      },
      {
        question_id: "65852923304e64caaaeb3cc1",
        question: "Resolution",
        section: "Directors",
        value: "0",
      },
      {
        question_id: "658529a1304e64caaaeb3cca",
        question: "Investigations completed",
        section: "Key Management Personnel",
        value: "10",
      },
      {
        question_id: "658529a1304e64caaaeb3cc9",
        question: "No's of complaints investigated",
        section: "Key Management Personnel",
        value: "10",
      },
      {
        question_id: "658529a1304e64caaaeb3cc8",
        question: "Complaints received",
        section: "Key Management Personnel",
        value: "10",
      },
      {
        question_id: "658529a1304e64caaaeb3ccb",
        question: "Resolution",
        section: "Key Management Personnel",
        value: "0",
      },
    ],
  },
  {
    task_name: "Conflict of interest cases",
    response: [
      {
        question_id: "65852923304e64caaaeb3cc0",
        question: "Investigations completed",
        section: "Directors",
        value: "10",
      },
      {
        question_id: "65852923304e64caaaeb3cbf",
        question: "No's of complaints investigated",
        section: "Directors",
        value: "10",
      },
      {
        question_id: "65852923304e64caaaeb3cbe",
        question: "Complaints received",
        section: "Directors",
        value: "10",
      },
      {
        question_id: "65852923304e64caaaeb3cc1",
        question: "Resolution",
        section: "Directors",
        value: "0",
      },
      {
        question_id: "658529a1304e64caaaeb3cca",
        question: "Investigations completed",
        section: "Key Management Personnel",
        value: "10",
      },
      {
        question_id: "658529a1304e64caaaeb3cc9",
        question: "No's of complaints investigated",
        section: "Key Management Personnel",
        value: "10",
      },
      {
        question_id: "658529a1304e64caaaeb3cc8",
        question: "Complaints received",
        section: "Key Management Personnel",
        value: "10",
      },
      {
        question_id: "658529a1304e64caaaeb3ccb",
        question: "Resolution",
        section: "Key Management Personnel",
        value: "0",
      },
    ],
  },
  {
    task_name: "Anti-Competitive Behaviour Cases",
    response: [
      {
        question_id: "65852a14304e64caaaeb3cd5",
        question: "Cases Registered",
        section: "No's of cases",
        value: "15",
      },
      {
        question_id: "65852a14304e64caaaeb3cd6",
        question: "Cases Pending",
        section: "No's of cases",
        value: "2",
      },
      {
        question_id: "65852a14304e64caaaeb3cd7",
        question: "Average monetary penalty",
        section: "No's of cases",
        value: "0",
      },
    ],
  },
  {
    task_name: "Impact Assessment",
    response: [
      {
        question_id: "6585425e304e64caaaeb3d05",
        question: "Details of Project",
        section: "Social Impact Assessment-1",
        value: "10",
      },
      {
        question_id: "6585425e304e64caaaeb3d09",
        question: "Results communicated in public domain",
        section: "Social Impact Assessment-1",
        value: {
          displayText: "Yes",
        },
      },
      {
        question_id: "6585425e304e64caaaeb3d08",
        question: "Has the assessment been conducted by external agency",
        section: "Social Impact Assessment-1",
        value: {
          displayText: "Yes",
        },
      },
      {
        question_id: "6585425e304e64caaaeb3d0b",
        question: "Negative Social Impact Identified-1",
        section: "Social Impact Assessment-1",
        value: "2",
      },
      {
        question_id: "6585425e304e64caaaeb3d0c",
        question: "Mitigation Measure - 1",
        section: "Social Impact Assessment-1",
        value: "2",
      },
      {
        question_id: "6585425e304e64caaaeb3d04",
        question: "Name of Project - 1",
        section: "Social Impact Assessment-1",
        value: "5",
      },
      {
        question_id: "6585425e304e64caaaeb3d0a",
        question: "Web Link",
        section: "Social Impact Assessment-1",
        value: "2",
      },
      {
        question_id: "6585425e304e64caaaeb3d06",
        question: "SIA Notification number",
        section: "Social Impact Assessment-1",
        value: "2",
      },
      {
        question_id: "6585425e304e64caaaeb3d07",
        question: "Date of Notification",
        section: "Social Impact Assessment-1",
        value: "5",
      },
      {
        question_id: "6585425e304e64caaaeb3d0d",
        question: "Mitigation Measure - 2",
        section: "Social Impact Assessment-1",
        value: "2",
      },
      {
        question_id: "65854382304e64caaaeb3d1a",
        question: "Name of Project - 2",
        section: "Social Impact Assessment-2",
        value: "10",
      },
      {
        question_id: "65854382304e64caaaeb3d20",
        question: "Web Link",
        section: "Social Impact Assessment-2",
        value: "5",
      },
      {
        question_id: "65854382304e64caaaeb3d1f",
        question: "Results communicated in public domain",
        section: "Social Impact Assessment-2",
        value: {
          displayText: "Yes",
        },
      },
      {
        question_id: "65854382304e64caaaeb3d22",
        question: "Mitigation Measure - 1",
        section: "Social Impact Assessment-2",
        value: "5",
      },
      {
        question_id: "65854382304e64caaaeb3d1c",
        question: "SIA Notification number",
        section: "Social Impact Assessment-2",
        value: "5",
      },
      {
        question_id: "65854382304e64caaaeb3d1d",
        question: "Date of Notification",
        section: "Social Impact Assessment-2",
        value: "4",
      },
      {
        question_id: "65854382304e64caaaeb3d1b",
        question: "Details of Project",
        section: "Social Impact Assessment-2",
        value: "5",
      },
      {
        question_id: "65854382304e64caaaeb3d23",
        question: "Mitigation Measure - 2",
        section: "Social Impact Assessment-2",
        value: "5",
      },
      {
        question_id: "65854382304e64caaaeb3d21",
        question: "Negative Social Impact Identified-1",
        section: "Social Impact Assessment-2",
        value: "4",
      },
      {
        question_id: "65854382304e64caaaeb3d1e",
        question: "Has the assessment been conducted by external agency",
        section: "Social Impact Assessment-2",
        value: {
          displayText: "Yes",
        },
      },
    ],
  },
  {
    task_name: "Monetary Penalities",
    response: [
      {
        question_id: "65855115304e64caaaeb3dac",
        question: "Amount in Rs",
        section: "Case Name-1",
        value: "10",
      },
      {
        question_id: "65855115304e64caaaeb3da9",
        question: "Case Details",
        section: "Case Name-1",
        value: "10",
      },
      {
        question_id: "65855115304e64caaaeb3dab",
        question: "Associated NGRBC principle",
        section: "Case Name-1",
        value: "10",
      },
      {
        question_id: "65855115304e64caaaeb3daa",
        question: "Name of the Regulatory agency / judicial institutions",
        section: "Case Name-1",
        value: "10",
      },
      {
        question_id: "65855115304e64caaaeb3dad",
        question: "Has the case been appealed",
        section: "Case Name-1",
        value: {
          displayText: "No",
        },
      },
      {
        question_id: "65855115304e64caaaeb3da8",
        question: "Name of Case-1",
        section: "Case Name-1",
        value: "10",
      },
      {
        question_id: "65855544304e64caaaeb3dbb",
        question: "Has the case been appealed",
        section: "Case Name-2",
        value: {
          displayText: "No",
        },
      },
      {
        question_id: "65855544304e64caaaeb3dba",
        question: "Amount in Rs",
        section: "Case Name-2",
        value: "10",
      },
      {
        question_id: "65855544304e64caaaeb3db8",
        question: "Name of the Regulatory agency / judicial institutions",
        section: "Case Name-2",
        value: "10",
      },
      {
        question_id: "65855544304e64caaaeb3db6",
        question: "Name of Case-2",
        section: "Case Name-2",
        value: "10",
      },
      {
        question_id: "65855544304e64caaaeb3db7",
        question: "Case Details",
        section: "Case Name-2",
        value: "10",
      },
      {
        question_id: "65855544304e64caaaeb3db9",
        question: "Associated NGRBC principle",
        section: "Case Name-2",
        value: "10",
      },
    ],
  },
  {
    task_name: "Non-Monetary Penalities",
    response: [
      {
        question_id: "65855706304e64caaaeb3dce",
        question: "Has the case been appealed",
        section: "Case Name-1",
        value: {
          displayText: "Yes",
        },
      },
      {
        question_id: "65855706304e64caaaeb3dc9",
        question: "Name of Case-1",
        section: "Case Name-1",
        value: "1",
      },
      {
        question_id: "65855706304e64caaaeb3dcb",
        question: "Name of the Regulatory agency / judicial institutions",
        section: "Case Name-1",
        value: "0",
      },
      {
        question_id: "65855706304e64caaaeb3dcc",
        question: "Associated NGRBC principle",
        section: "Case Name-1",
        value: "0",
      },
      {
        question_id: "65855706304e64caaaeb3dcd",
        question: "Punishment type",
        section: "Case Name-1",
        value: "0",
      },
      {
        question_id: "65855706304e64caaaeb3dca",
        question: "Case Details",
        section: "Case Name-1",
        value: "0",
      },
      {
        question_id: "658557de304e64caaaeb3ddc",
        question: "Has the case been appealed",
        section: "Case Name-2",
        value: {
          displayText: "No",
        },
      },
      {
        question_id: "658557de304e64caaaeb3dda",
        question: "Associated NGRBC principle",
        section: "Case Name-2",
        value: "0",
      },
      {
        question_id: "658557de304e64caaaeb3dd7",
        question: "Name of Case-2",
        section: "Case Name-2",
        value: "0",
      },
      {
        question_id: "658557de304e64caaaeb3ddb",
        question: "Punishment type",
        section: "Case Name-2",
        value: "0",
      },
      {
        question_id: "658557de304e64caaaeb3dd9",
        question: "Name of the Regulatory agency / judicial institutions",
        section: "Case Name-2",
        value: "0",
      },
      {
        question_id: "658557de304e64caaaeb3dd8",
        question: "Case Details",
        section: "Case Name-2",
        value: "0",
      },
    ],
  },
  {
    task_name: "Project Rehabilitation",
    response: [
      {
        question_id: "65855a73304e64caaaeb3df0",
        question: "Amount paid to PAF in FY",
        section: "Project for which R&R is ongoing - 1",
        value: "10",
      },
      {
        question_id: "65855a73304e64caaaeb3deb",
        question: "Name of Project for which R&R is ongoing - 1",
        section: "Project for which R&R is ongoing - 1",
        value: "10",
      },
      {
        question_id: "65855a73304e64caaaeb3ded",
        question: "District",
        section: "Project for which R&R is ongoing - 1",
        value: "10",
      },
      {
        question_id: "65855a73304e64caaaeb3dee",
        question: "No. of Project afected families",
        section: "Project for which R&R is ongoing - 1",
        value: "9",
      },
      {
        question_id: "65855a73304e64caaaeb3dec",
        question: "State",
        section: "Project for which R&R is ongoing - 1",
        value: "10",
      },
      {
        question_id: "65855a73304e64caaaeb3def",
        question: "% PAF covered by R&R",
        section: "Project for which R&R is ongoing - 1",
        value: "10",
      },
      {
        question_id: "65855be1304e64caaaeb3dfd",
        question: "District",
        section: "Project for which R&R is ongoing - 2",
        value: "10",
      },
      {
        question_id: "65855be1304e64caaaeb3dff",
        question: "% PAF covered by R&R",
        section: "Project for which R&R is ongoing - 2",
        value: "10",
      },
      {
        question_id: "65855be1304e64caaaeb3dfe",
        question: "No. of Project affected families",
        section: "Project for which R&R is ongoing - 2",
        value: "10",
      },
      {
        question_id: "65855be1304e64caaaeb3dfc",
        question: "State",
        section: "Project for which R&R is ongoing - 2",
        value: "10",
      },
      {
        question_id: "65855be1304e64caaaeb3dfb",
        question: "Name of Project for which R&R is ongoing - 1",
        section: "Project for which R&R is ongoing - 2",
        value: "10",
      },
    ],
  },
  {
    task_name: "Disciplinary Actions",
    response: [
      {
        question_id: "65854408304e64caaaeb3d36",
        question: "Investigations completed",
        section: "Board of Directors",
        value: "10",
      },
      {
        question_id: "65854408304e64caaaeb3d35",
        question: "No's of complaints investigated",
        section: "Board of Directors",
        value: "10",
      },
      {
        question_id: "65854408304e64caaaeb3d37",
        question: "Resolution",
        section: "Board of Directors",
        value: "10",
      },
      {
        question_id: "65854408304e64caaaeb3d34",
        question: "Complaints resolved",
        section: "Board of Directors",
        value: "9",
      },
      {
        question_id: "65854408304e64caaaeb3d33",
        question: "No's of complaints",
        section: "Board of Directors",
        value: "10",
      },
      {
        question_id: "6585448d304e64caaaeb3d42",
        question: "Investigations completed",
        section: "Key Management Personnel",
        value: "10",
      },
      {
        question_id: "6585448d304e64caaaeb3d43",
        question: "Resolution",
        section: "Key Management Personnel",
        value: "1",
      },
      {
        question_id: "6585448d304e64caaaeb3d41",
        question: "No's of complaints investigated",
        section: "Key Management Personnel",
        value: "9",
      },
      {
        question_id: "6585448d304e64caaaeb3d3f",
        question: "No's of complaints",
        section: "Key Management Personnel",
        value: "10",
      },
      {
        question_id: "6585448d304e64caaaeb3d40",
        question: "Complaints resolved",
        section: "Key Management Personnel",
        value: "9",
      },
      {
        question_id: "65854574304e64caaaeb3d4b",
        question: "No's of complaints",
        section: "Employees other than Key Management Personnel",
        value: "10",
      },
      {
        question_id: "65854574304e64caaaeb3d4d",
        question: "No's of complaints investigated",
        section: "Employees other than Key Management Personnel",
        value: "9",
      },
      {
        question_id: "65854574304e64caaaeb3d4f",
        question: "Resolution",
        section: "Employees other than Key Management Personnel",
        value: "9",
      },
      {
        question_id: "65854574304e64caaaeb3d4c",
        question: "Complaints resolved",
        section: "Employees other than Key Management Personnel",
        value: "9",
      },
      {
        question_id: "65854574304e64caaaeb3d4e",
        question: "Investigations completed",
        section: "Employees other than Key Management Personnel",
        value: "9",
      },
      {
        question_id: "658545d1304e64caaaeb3d5b",
        question: "Resolution",
        section: "Workers",
        value: "9",
      },
      {
        question_id: "658545d1304e64caaaeb3d58",
        question: "Complaints resolved",
        section: "Workers",
        value: "10",
      },
      {
        question_id: "658545d1304e64caaaeb3d59",
        question: "No's of complaints investigated",
        section: "Workers",
        value: "8",
      },
      {
        question_id: "658545d1304e64caaaeb3d57",
        question: "No's of complaints",
        section: "Workers",
        value: "10",
      },
      {
        question_id: "658545d1304e64caaaeb3d5a",
        question: "Investigations completed",
        section: "Workers",
        value: "9",
      },
      {
        question_id: "6585464e304e64caaaeb3d63",
        question: "No's of complaints",
        section: "Contract Workers",
        value: "12",
      },
      {
        question_id: "6585464e304e64caaaeb3d64",
        question: "Complaints resolved",
        section: "Contract Workers",
        value: "7",
      },
      {
        question_id: "6585464e304e64caaaeb3d65",
        question: "No's of complaints investigated",
        section: "Contract Workers",
        value: "8",
      },
      {
        question_id: "6585464e304e64caaaeb3d66",
        question: "Investigations completed",
        section: "Contract Workers",
        value: "9",
      },
      {
        question_id: "6585464e304e64caaaeb3d67",
        question: "Resolution",
        section: "Contract Workers",
        value: "9",
      },
    ],
  },
  {
    task_name: "Product Safety",
    response: [
      {
        question_id: "6585468d304e64caaaeb3d70",
        question: "No's of complaints",
        section: "Product Safety Complaints",
        value: "12",
      },
      {
        question_id: "6585468d304e64caaaeb3d71",
        question: "Complaints resolved",
        section: "Product Safety Complaints",
        value: "11",
      },
      {
        question_id: "6585468d304e64caaaeb3d6f",
        question: "Average compensation paid out",
        section: "Product Safety Complaints",
        value: "10",
      },
    ],
  },
  {
    task_name: "Cases with Law enforcement agencies",
    response: [
      {
        question_id: "65f1478ef3ae67c47ee51aff",
        question: "Cases with BOD",
        section: "BOD",
        value: "11",
      },
      {
        question_id: "65f1478ef3ae67c47ee51b00",
        question: "Average monetary penalty",
        section: "BOD",
        value: "13",
      },
      {
        question_id: "65f1481df3ae67c47ee51b05",
        question: "Cases with KMP",
        section: "KMP",
        value: "10",
      },
      {
        question_id: "65f1481df3ae67c47ee51b06",
        question: "Average monetary penalty",
        section: "KMP",
        value: "14",
      },
    ],
  },
];

module.exports =  legalDataSet ;
